services: 
  auth:
    build: ./service-auth-node
    ports:
      - "3000:3000"

  ledger:
    build: ./service-ledger-go
    ports:
      - "4000:4000"

  fraud:
    build: ./service-fraud-python
    ports:
      - "5000:5000"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass


  redis:
    image: redis:7