apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: xibank
type: Opaque
stringData:
  secret: notsosecret

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: xibank
type: Opaque
stringData:
  password: password

