apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: xibank
spec:
  selector:
    app: auth
  ports:
    - port: 3000


---
apiVersion: v1
kind: Service
metadata:
name: ledger
namespace: xibank
spec:
selector:
app: ledger
ports:
- port: 4000


---
apiVersion: v1
kind: Service
metadata:
name: fraud
namespace: xibank
spec:
selector:
app: fraud
ports:
- port: 5000


---
apiVersion: v1
kind: Service
metadata:
name: postgres
namespace: xibank
spec:
selector:
app: postgres
ports:
- port: 5432
